version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: isviable-btc-shell_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: horologger/btcshell:v0.0.3
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_BITCOIN_DATA_DIR}:/data/.bitcoin:ro
    environment:
      # BTC
      BTC_RPC_HOST: "${APP_BITCOIN_NODE_IP}"
      BTC_RPC_PORT: "${APP_BITCOIN_RPC_PORT}"
      BTC_RPC_USER: "${APP_BITCOIN_RPC_USER}"
      BTC_RPC_PASSWORD: "${APP_BITCOIN_RPC_PASS}"

      # App
      APP_HIDDEN_SERVICE: http://$APP_HIDDEN_SERVICE
      APP_USER: "admin"
      APP_PASSWORD: "$APP_PASSWORD"
      APP_DOMAIN: $APP_DOMAIN
      GOTTY_PORT: 8080
      PORT: 8080
